# Assignment 01: Part-of-Speech (POS) Extraction from a News Article

**Name:** Aakash Bhusal  
**Course:** Natural Language Processing  
**Assignment:** Assignment 01  
**Topic:** POS Extraction from a News Article

## Objective

The objective of this assignment is to apply Natural Language Processing
techniques to identify and extract nouns and verbs from an English-language
news article.

The article is first loaded from a plain text file. The text is then
tokenized and POS tagged using the NLTK library. Finally, nouns and verbs
are extracted and saved into a CSV file.

## Introduction

Part-of-Speech (POS) tagging is an important Natural Language Processing
technique in which each word in a sentence is assigned a grammatical
category such as noun, verb, adjective, adverb, pronoun, or preposition.

In this assignment, an English news article is analyzed using POS tagging.
The main focus is on extracting nouns and verbs from the article.

The Natural Language Toolkit (NLTK) is used for tokenization and
Part-of-Speech tagging, while Pandas is used to organize and export the
results.

**Installing NLTK and pandas**

In [1]:
%pip install nltk pandas matplotlib

Requirement already satisfied: nltk in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.10.3)
Requirement already satisfied: pandas in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: matplotlib in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.11.1)
Requirement already satisfied: defusedxml in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nltk) (8.4.2)
Requirement already satisfied: joblib in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nltk) (2026.2.19)
Requirement already satisfied: tqdm in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=9 in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\Users\aakas\AppData\Local\Programs\Python\Python314\Lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

**Importing Libraries**

In [2]:
import nltk
import pandas as pd
import re
import matplotlib.pyplot as plt

**Download NLTK Resources**

These resources are required for word tokenization and POS tagging.

In [3]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\aakas\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\aakas\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\aakas\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\aakas\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

**Load the News Article**

This gives us a basic idea about the size of the article.

In [4]:
# Load the news article from the text file

with open("news_article.txt", "r", encoding="utf-8") as file:
    text = file.read()

print("Article loaded successfully.")
print("\nArticle:")
print(text)

Article loaded successfully.

Article:
Former BBC Business anchor and global financial commentator Susannah Streeter will headline the second Tech Talk Wales event at the Celtic Manor Resort this month. Streeter, now Chief Investment Strategist at
 Wealth Club, will discuss how technology, investment, and business growth are increasingly intertwined when the event returns on Thursday. The free event will bring together members of Wales' growing technology
 community to discuss emerging trends, investment opportunities, and challenges facing businesses. The discussion will explore emerging trends and market developments alongside the opportunities available to organisations
 seeking to harness new technology for growth.

**Inspect the Article**

The regular expression replaces multiple spaces, tabs, and line breaks with a single space.

In [5]:
print("Number of characters:", len(text))
print("Number of words before tokenization:", len(text.split()))

Number of characters: 689
Number of words before tokenization: 94

**Text Preprocessing**

In [6]:
# Remove unnecessary whitespace

text = re.sub(r'\s+', ' ', text).strip()

print(text)

Former BBC Business anchor and global financial commentator Susannah Streeter will headline the second Tech Talk Wales event at the Celtic Manor Resort this month. Streeter, now Chief Investment Strategist at Wealth Club, will discuss how technology, investment, and business growth are increasingly intertwined when the event returns on Thursday. The free event will bring together members of Wales' growing technology community to discuss emerging trends, investment opportunities, and challenges facing businesses. The discussion will explore emerging trends and market developments alongside the opportunities available to organisations seeking to harness new technology for growth.

**Tokenization**

The article is converted from a continuous sequence of text into individual tokens.

In [7]:
# Tokenize the article into individual words/tokens

tokens = nltk.word_tokenize(text)

print("Total number of tokens:", len(tokens))
print("\nFirst 30 tokens:")
print(tokens[:30])

Total number of tokens: 105

First 30 tokens:
['Former', 'BBC', 'Business', 'anchor', 'and', 'global', 'financial', 'commentator', 'Susannah', 'Streeter', 'will', 'headline', 'the', 'second', 'Tech', 'Talk', 'Wales', 'event', 'at', 'the', 'Celtic', 'Manor', 'Resort', 'this', 'month', '.', 'Streeter', ',', 'now', 'Chief']

**POS Tagging**

In [8]:
# Perform Part-of-Speech tagging

pos_tags = nltk.pos_tag(tokens)

print("First 30 POS-tagged tokens:\n")

for word, tag in pos_tags[:30]:
    print(f"{word:20} {tag}")

First 30 POS-tagged tokens:

Former               NNP
BBC                  NNP
Business             NNP
anchor               NN
and                  CC
global               JJ
financial            JJ
commentator          NN
Susannah             NNP
Streeter             NNP
will                 MD
headline             VB
the                  DT
second               JJ
Tech                 NNP
Talk                 NNP
Wales                NNP
event                NN
at                   IN
the                  DT
Celtic               NNP
Manor                NNP
Resort               NNP
this                 DT
month                NN
.                    .
Streeter             NNP
,                    ,
now                  RB
Chief                NNP

**Identify Noun and Verb Tags**

In [9]:
# POS tags representing nouns

noun_tags = [
    'NN',    # singular noun
    'NNS',   # plural noun
    'NNP',   # proper singular noun
    'NNPS'   # proper plural noun
]

# POS tags representing verbs

verb_tags = [
    'VB',    # base form
    'VBD',   # past tense
    'VBG',   # gerund/present participle
    'VBN',   # past participle
    'VBP',   # non-3rd person singular present
    'VBZ'    # 3rd person singular present
]

**Extract Nouns and Verbs**

In [10]:
# Extract nouns and verbs

noun_verb_data = []

for word, tag in pos_tags:
    if tag in noun_tags or tag in verb_tags:
        noun_verb_data.append((word, tag))

print("Total nouns and verbs extracted:", len(noun_verb_data))

print("\nFirst 30 extracted words:")
print(noun_verb_data[:30])

Total nouns and verbs extracted: 59

First 30 extracted words:
[('Former', 'NNP'), ('BBC', 'NNP'), ('Business', 'NNP'), ('anchor', 'NN'), ('commentator', 'NN'), ('Susannah', 'NNP'), ('Streeter', 'NNP'), ('headline', 'VB'), ('Tech', 'NNP'), ('Talk', 'NNP'), ('Wales', 'NNP'), ('event', 'NN'), ('Celtic', 'NNP'), ('Manor', 'NNP'), ('Resort', 'NNP'), ('month', 'NN'), ('Streeter', 'NNP'), ('Chief', 'NNP'), ('Investment', 'NNP'), ('Strategist', 'NN'), ('Wealth', 'NNP'), ('Club', 'NNP'), ('discuss', 'VB'), ('technology', 'NN'), ('investment', 'NN'), ('business', 'NN'), ('growth', 'NN'), ('are', 'VBP'), ('intertwined', 'VBN'), ('event', 'NN')]

**Create a DataFrame**

In [11]:
df = pd.DataFrame(
    noun_verb_data,
    columns=["Word", "POS_Tag"]
)

df.head(20)

           Word POS_Tag
0        Former     NNP
1           BBC     NNP
2      Business     NNP
3        anchor      NN
4   commentator      NN
5      Susannah     NNP
6      Streeter     NNP
7      headline      VB
8          Tech     NNP
9          Talk     NNP
10        Wales     NNP
11        event      NN
12       Celtic     NNP
13        Manor     NNP
14       Resort     NNP
15        month      NN
16     Streeter     NNP
17        Chief     NNP
18   Investment     NNP
19   Strategist      NN

**Add Noun/Verb Category**

In [12]:
def get_pos_category(tag):

    if tag in noun_tags:
        return "Noun"

    elif tag in verb_tags:
        return "Verb"

    return "Other"


df["POS_Category"] = df["POS_Tag"].apply(get_pos_category)

df.head(20)

           Word POS_Tag POS_Category
0        Former     NNP         Noun
1           BBC     NNP         Noun
2      Business     NNP         Noun
3        anchor      NN         Noun
4   commentator      NN         Noun
5      Susannah     NNP         Noun
6      Streeter     NNP         Noun
7      headline      VB         Verb
8          Tech     NNP         Noun
9          Talk     NNP         Noun
10        Wales     NNP         Noun
11        event      NN         Noun
12       Celtic     NNP         Noun
13        Manor     NNP         Noun
14       Resort     NNP         Noun
15        month      NN         Noun
16     Streeter     NNP         Noun
17        Chief     NNP         Noun
18   Investment     NNP         Noun
19   Strategist      NN         Noun

**Display All Extracted Nouns**

In [13]:
nouns = df[df["POS_Category"] == "Noun"]

print("Extracted Nouns:")
display(nouns)

Extracted Nouns:

             Word POS_Tag POS_Category
0          Former     NNP         Noun
1             BBC     NNP         Noun
2        Business     NNP         Noun
3          anchor      NN         Noun
4     commentator      NN         Noun
5        Susannah     NNP         Noun
6        Streeter     NNP         Noun
8            Tech     NNP         Noun
9            Talk     NNP         Noun
10          Wales     NNP         Noun
11          event      NN         Noun
12         Celtic     NNP         Noun
13          Manor     NNP         Noun
14         Resort     NNP         Noun
15          month      NN         Noun
16       Streeter     NNP         Noun
17          Chief     NNP         Noun
18     Investment     NNP         Noun
19     Strategist      NN         Noun
20         Wealth     NNP         Noun
21           Club     NNP         Noun
23     technology      NN         Noun
24     investment      NN         Noun
25       business      NN         Noun
26         growth      NN         Noun
29          event      NN         Noun
30        returns     NNS         Noun
31       Thursday     NNP         Noun
32          event      NN         Noun
34        members     NNS         Noun
35          Wales     NNP         Noun
37     technology      NN         Noun
38      community      NN         Noun
41         trends     NNS         Noun
42     investment      NN         Noun
43  opportunities     NNS         Noun
44     challenges     NNS         Noun
46     businesses     NNS         Noun
47     discussion      NN         Noun
50         trends     NNS         Noun
51         market      NN         Noun
52   developments     NNS         Noun
53  opportunities     NNS         Noun
54  organisations     NNS         Noun
57     technology      NN         Noun
58         growth      NN         Noun

**Display All Extracted Verbs**

In [14]:
verbs = df[df["POS_Category"] == "Verb"]

print("Extracted Verbs:")
display(verbs)

Extracted Verbs:

           Word POS_Tag POS_Category
7      headline      VB         Verb
22      discuss      VB         Verb
27          are     VBP         Verb
28  intertwined     VBN         Verb
33        bring      VB         Verb
36      growing     VBG         Verb
39      discuss      VB         Verb
40     emerging     VBG         Verb
45       facing     VBG         Verb
48      explore      VB         Verb
49     emerging     VBG         Verb
55      seeking     VBG         Verb
56      harness      VB         Verb

**Count Nouns and Verbs**

In [15]:
noun_count = len(nouns)
verb_count = len(verbs)

print("Total Nouns:", noun_count)
print("Total Verbs:", verb_count)

Total Nouns: 46
Total Verbs: 13

**POS Frequency Analysis**

In [16]:
print("Frequency of POS Categories:")
print(df["POS_Category"].value_counts())

Frequency of POS Categories:
POS_Category
Noun    46
Verb    13
Name: count, dtype: int64

In [17]:
print("\nFrequency of Individual POS Tags:")
print(df["POS_Tag"].value_counts())

Frequency of Individual POS Tags:
POS_Tag
NNP    18
NN     18
NNS    10
VB      6
VBG     5
VBP     1
VBN     1
Name: count, dtype: int64

**Save Results to CSV**

In [18]:
output_file = "AakashBhusal_POS_01.csv"

df.to_csv(output_file, index=False)

print(f"CSV file successfully saved as: {output_file}")

CSV file successfully saved as: AakashBhusal_POS_01.csv